default:
  image: amazoncorretto:17

cache:
  - key: maven-cache
    paths:
      - .m2/repository
  - key: target-cache
    paths:
      - ./target

variables:
  MAVEN_CLI_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

build:compile:
  stage: build
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean compile
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

verify:development:
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' `find . -name jacoco.csv -print`
    - bash <(curl -Ls https://coverage.codacy.com/get.sh)
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  coverage: '/(\d+\.?\d*) \% covered/'
  artifacts:
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: jacoco
        path: '**/jacoco.xml'
      junit:
        - '**/TEST-io.gitlab.vitalijr2.ridecost.estimator.*.xml'

verify:default:
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' `find . -name jacoco.csv -print`
    - bash <(curl -Ls https://coverage.codacy.com/get.sh)
    - ./mvnw license:check-file-header -Dlicense.failOnMissingHeader=true -Pprepare-and-check
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  coverage: '/(\d+\.?\d*) \% covered/'
  artifacts:
    expire_in: 1 year
    reports:
      coverage_report:
        coverage_format: jacoco
        path: '**/jacoco.xml'
      junit:
        - '**/TEST-io.gitlab.vitalijr2.ridecost.estimator.*.xml'

verify:merge-request:
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' `find . -name jacoco.csv -print`
    - bash <(curl -Ls https://coverage.codacy.com/get.sh)
    - ./mvnw license:check-file-header -Dlicense.failOnMissingHeader=true -Pprepare-and-check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - when: never
  coverage: '/(\d+\.?\d*) \% covered/'
  artifacts:
    expire_in: 1 day

deploy:publishing:
  stage: deploy
  script:
    - ./mvnw -s .mvn/ci_settings.xml -DskipTests -Prelease
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
